get basic live tests working

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -19,6 +19,9 @@
 #   $ RBENV_VERSIONS="1.9.3-p194 ree-1.8.7-2012.02" script/test
 set -e
 
+port=3999
+scheme=http
+
 find_test_files() {
   find "$1" -name '*_test.rb'
 }
@@ -28,6 +31,32 @@ filter_matching() {
   shift
   for line in "$@"; do
     [[ $line == *"$pattern"* ]] && echo "$line"
+  done
+}
+
+start_server() {
+  mkdir -p log
+  script/server -p $port >log/test.log 2>&1 &
+  echo $!
+}
+
+server_started() {
+  lsof -i :${1?} >/dev/null
+}
+
+timestamp() {
+  date +%s
+}
+
+wait_for_server() {
+  timeout=$(( `timestamp` + $1 ))
+  while true; do
+    if server_started "$2"; then
+      break
+    elif [ `timestamp` -gt "$timeout" ]; then
+      echo "timed out after $1 seconds" >&2
+      return 1
+    fi
   done
 }
 
@@ -65,6 +94,28 @@ if [ -n "$filtered" ]; then
     test_files=(${explicit_files[@]})
     echo running "${test_files[@]}"
   fi
+fi
+
+# If there are live tests, spin up the HTTP server
+if [ -n "$(filter_matching "live" "${test_files[@]}")" ]; then
+  if server_started $port; then
+    echo "aborted: another instance of server running on $port" >&2
+    exit 1
+  fi
+  server_pid=$(start_server)
+  wait_for_server 30 $port || {
+    cat log/test.log
+    kill "$server_pid"
+    exit 1
+  }
+  cleanup() {
+    if [ $? -ne 0 ] && [ -n "$TRAVIS" ]; then
+      cat log/test.log
+    fi
+    kill "$server_pid"
+  }
+  trap cleanup INT EXIT
+  export HURLEY_LIVE="${scheme}://localhost:${port}"
 fi
 
 warnings="${TMPDIR:-/tmp}/faraday-warnings.$$"
